const ENTITY_TYPE_ANY = -1,
  ENTITY_TYPE_ENTITY = 0,
  ENTITY_TYPE_COMMAND = 1,
  ENTITY_TYPE_USER = 2,
  ENTITY_TYPE_TAG = 3,
  ENTITY_TYPE_COMMENT = 4,
  ENTITY_TYPE_TAG_APPLICATION = 5,
  ENTITY_TYPE_TAG_APPLICATION_RATIFICATION = 6;

module.exports = {
  ENTITY_TYPE_ANY,
  ENTITY_TYPE_ENTITY,
  ENTITY_TYPE_COMMAND,
  ENTITY_TYPE_USER,
  ENTITY_TYPE_TAG,
  ENTITY_TYPE_COMMENT,
  ENTITY_TYPE_TAG_APPLICATION,
  ENTITY_TYPE_TAG_APPLICATION_RATIFICATION
};
